import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {verifyAsrBundle,alignAsrCuesToFrames,hasTrustedAsrFrameBoundary,parseSrt} from '../render-worker/asr-frame-boundary.mjs';
const hash=x=>createHash('sha256').update(x).digest('hex');
function fixture(){
 const sourceBytes=Buffer.from('isolated-source'),srtBytes=Buffer.from('1\n00:00:10,400 --> 00:00:16,000\n说话人 1: 完整产品说明。\n');
 const source={id:'source',productCategory:'water',skuVersion:'2026-test',sha256:hash(sourceBytes),srtSha256:hash(srtBytes),minuteToken:'minute-test',durationSeconds:20};
 return {source,sourceBytes,srtBytes,receipts:{drive:{ok:true,identity:'user',data:{size:sourceBytes.length,file_token:'file',version:'1'}},minute:{ok:true,identity:'user',data:{minute_token:'minute-test'}},detail:{ok:true,identity:'user',data:{minutes:[{minute_token:'minute-test'}]}},export:{size_bytes:srtBytes.length}},frameMap:{sourceSha256:source.sha256,starts:Array.from({length:600},(_,i)=>i/30),end:20}};
}
test('10.40秒真实句界保持原时间，不因不是整数秒被判缺源',()=>{const x=fixture(),r=alignAsrCuesToFrames(verifyAsrBundle(x))[0];assert.equal(r.startSeconds,10.4);assert.equal(r.endSeconds,16);assert.equal(r.startFrame,312);assert.equal(r.nativeFrameAligned,true);assert.equal(r.integerSecondAligned,false);assert.equal(r.requiresReview,true);assert.equal(r.boundaryEvidence.sourceSha256,x.source.sha256);});
test('按真实帧时间向外不足一帧，完整包住语音且保留原文',()=>{const x=fixture();const b=verifyAsrBundle(x);b.cues=[{cueId:1,start:10.41,end:16.013,text:'不能少字。'}];const r=alignAsrCuesToFrames(b)[0];assert.equal(r.startFrame,312);assert.equal(r.endFrame,481);assert.ok(r.startSeconds<=10.41&&r.endSeconds>=16.013);assert.ok(10.41-r.startSeconds<1/30&&r.endSeconds-16.013<1/30);assert.equal(r.label,'不能少字。');});
test('可变帧率使用实际PTS，不猜固定帧率',()=>{const x=fixture(),b=verifyAsrBundle(x);b.frameMap={starts:[0,.02,.06,.10,.15,.20,.25,.30,.4,.5,.6,.7,.8,.9,1,1.04,1.08],end:1.12};b.cues=[{cueId:1,start:.01,end:1.02,text:'完整。'}];const r=alignAsrCuesToFrames(b)[0];assert.equal(r.startSeconds,0);assert.equal(r.endSeconds,1.04);assert.equal(r.nativeFrameAligned,true);});
for(const kind of ['source','srt','minute','export','frames','identity'])test('拒绝错误或缺失证据 '+kind,()=>{const x=fixture();if(kind==='source')x.sourceBytes=Buffer.from('changed');if(kind==='srt')x.srtBytes=Buffer.from('changed');if(kind==='minute')x.receipts.detail.data.minutes[0].minute_token='other';if(kind==='export')x.receipts.export.size_bytes++;if(kind==='frames')x.frameMap.sourceSha256=hash('other');if(kind==='identity')x.receipts.detail.identity='bot';assert.throws(()=>verifyAsrBundle(x));});
test('拒绝乱序或重叠ASR、不根据文字杜撰长句中间切点',()=>{assert.throws(()=>parseSrt(Buffer.from('1\n00:00:01,000 --> 00:00:03,000\n第一句\n\n2\n00:00:02,000 --> 00:00:04,000\n第二句'),10));const b=verifyAsrBundle(fixture());b.cues=[{cueId:1,start:0,end:21,text:'不能按字数切'}];b.frameMap={starts:Array.from({length:900},(_,i)=>i/30),end:30};const r=alignAsrCuesToFrames(b)[0];assert.equal(r.endSeconds,21);assert.equal(r.nativeFrameAligned,false);assert.equal(r.requiresReview,true);});
test('短片不补到0.8秒；音轨超过末帧不截断冒充完整句',()=>{const b=verifyAsrBundle(fixture());b.cues=[{cueId:1,start:0,end:.3,text:'短句'},{cueId:2,start:19,end:20.1,text:'尾音'}];const r=alignAsrCuesToFrames(b);assert.ok(r.every(v=>!v.nativeFrameAligned));assert.equal(r[0].durationSeconds,.3);});
test('正文、source、SKU与SHA变化不能继承原帧边界核验',()=>{const x=fixture(),r=alignAsrCuesToFrames(verifyAsrBundle(x))[0],s={id:'source',contentSha256:x.source.sha256,productCategory:'water',skuVersion:'2026-test',durationSeconds:20};assert.equal(hasTrustedAsrFrameBoundary(r,s),true);for(const changed of [{id:'other'},{contentSha256:hash('other')},{productCategory:'black'},{skuVersion:'2022'}])assert.equal(hasTrustedAsrFrameBoundary(r,{...s,...changed}),false);assert.equal(hasTrustedAsrFrameBoundary({...r,label:'改写'},s),false);assert.equal(hasTrustedAsrFrameBoundary({...r,requiresReview:false}, {...s,skuVersion:null}),false);});
