import test from 'node:test';import assert from 'node:assert/strict';
import {batchOutputInput,applyBatchOutputReview,batchInputsStillApproved} from '../render-worker/batch-output-review.mjs';
import {VISUAL_REVIEW_VERSION} from '../render-worker/visual-quality.mjs';
const hash='a'.repeat(64),sku='verified-fixture-sku';
function fixture(){const source={id:'source',storedName:'source.mp4',productCategory:'黑晶面膜',contentSha256:hash,skuVersion:sku,analysisAsrEvidence:{skuVersion:sku,sourceSha256:hash},speechSegments:[{startSeconds:0,endSeconds:6,text:'打开包装，取出面膜。'}]};const clip={id:'clip',sourceId:'source',productCategory:source.productCategory,reviewStatus:'approved',boundaryEvidence:{skuVersion:sku,sourceSha256:hash},startSeconds:0,endSeconds:6,durationSeconds:6,role:'solution'};const assessment={sha256:'b'.repeat(64),assessment:{checks:[...Array.from({length:4},(_,i)=>({name:'technical'+i,passed:true,detail:'verified'})),{name:'成片内容复核',passed:false,detail:'等待同批'}],status:'review_required',autoApproved:false}};return {source,clip,assessment};}
test('真实渲染参数保留旧单片cache键、同源SHA/SKU和原sourcePath，仅已验证SKU可进入',()=>{const f=fixture(),input=batchOutputInput({outputId:'render/1',filePath:'/output',assessment:f.assessment,clips:[f.clip],sources:[f.source],sourcePath:s=>'/source/'+s.storedName});assert.equal(input.technicalPassed,true);assert.equal(input.timeline[0].skuVersion,sku);assert.equal(input.timeline[0].sourceSha256,hash);assert.equal(input.sourceFiles[0].filePath,'/source/source.mp4');assert.equal(input.singleTimeline[0].sourceId,undefined);assert.equal(input.singleTimeline[0].skuVersion,undefined);assert.equal(input.singleTimeline[0].sourceText,'打开包装，取出面膜。');delete f.source.analysisAsrEvidence;const unknown=batchOutputInput({outputId:'render/1',filePath:'/output',assessment:f.assessment,clips:[f.clip],sources:[f.source],sourcePath:()=>'/source'});assert.equal(unknown.sourceFiles[0].skuVersion,null);assert.equal(unknown.timeline[0].skuVersion,null);});
test('缺片、错SHA不能改变技术检查或让等待态通过',()=>{for(const review of [null,{sha256:'c'.repeat(64),status:'passed',version:VISUAL_REVIEW_VERSION,confidence:1,issues:[]}]){const f=fixture(),variant={id:'1',contentSha256:f.assessment.sha256,automaticAssessment:f.assessment.assessment};applyBatchOutputReview(variant,review);assert.equal(variant.reviewStatus,'changes_requested');assert.equal(variant.automaticAssessment.autoApproved,false);assert.equal(variant.automaticAssessment.status,'review_required');assert.ok(variant.automaticAssessment.checks.slice(0,4).every(c=>c.passed));}});
test('单片最终审核重算，技术失败不能被视觉通过冲掉',()=>{const f=fixture(),review={sha256:f.assessment.sha256,status:'passed',version:VISUAL_REVIEW_VERSION,confidence:.95,issues:[],summary:'test'};for(const technicalPass of [true,false]){const prior=structuredClone(f.assessment.assessment);prior.checks[0].passed=technicalPass;const variant={id:'1',contentSha256:f.assessment.sha256,automaticAssessment:prior};applyBatchOutputReview(variant,review);assert.equal(variant.automaticAssessment.status,technicalPass?'passed':'failed');assert.equal(variant.automaticAssessment.autoApproved,technicalPass);}});
test('模型返回期间原SKU、SHA或切片批准变化时，保存前门禁拒绝',()=>{const f=fixture(),input=batchOutputInput({outputId:'render/1',filePath:'/output',assessment:f.assessment,clips:[f.clip],sources:[f.source],sourcePath:()=>'/source'});const original={sources:[f.source],clips:[f.clip]};assert.equal(batchInputsStillApproved([input],original),true);for(const mutate of [l=>l.clips[0].reviewStatus='changes_requested',l=>l.sources[0].skuVersion='new',l=>l.sources[0].contentSha256='c'.repeat(64),l=>l.sources[0].analysisAsrEvidence.skuVersion=null]){const library=structuredClone(original);mutate(library);assert.equal(batchInputsStillApproved([input],library),false);}});
test('旧SKU切片不能继承新源SKU，已批准切片改了原范围也不能沿用模型回执',()=>{const f=fixture();f.clip.boundaryEvidence.skuVersion='old-sku';let input=batchOutputInput({outputId:'render/1',filePath:'/output',assessment:f.assessment,clips:[f.clip],sources:[f.source],sourcePath:()=>'/source'});assert.equal(input.timeline[0].clipApproved,false);f.clip.boundaryEvidence.skuVersion=sku;input=batchOutputInput({outputId:'render/1',filePath:'/output',assessment:f.assessment,clips:[f.clip],sources:[f.source],sourcePath:()=>'/source'});f.clip.startSeconds=1;f.clip.endSeconds=7;assert.equal(batchInputsStillApproved([input],{sources:[f.source],clips:[f.clip]}),false);});
