import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {VisualQuality,parseVisualReview} from '../render-worker/visual-quality.mjs';
const timeline=[{clipId:'fixture',role:'solution',start:0,duration:10,sourceText:'打开包装，取出黑晶面膜。'}];
const env={WIS_REMIX_VISUAL_REVIEW_ENABLED:'true',JUMP_LLM_URL:'https://example.invalid/model',JUMP_LLM_TOKEN:'isolated-test-only',JUMP_LLM_APPLICATION:'test',JUMP_LLM_PROVIDER:'test',JUMP_LLM_VISION_MODEL:'vision-fixture'};
async function fixture(t,fetchImpl){const directory=await fs.mkdtemp(path.join(os.tmpdir(),'visual-qc-'));t.after(()=>fs.rm(directory,{recursive:true,force:true}));const review=new VisualQuality({directory,env,runProcess:async(_cmd,args)=>fs.writeFile(args.at(-1),'fixture-image'),fetchImpl});return review;}
test('只有结构完整、高置信且没有问题的内容结论可通过',()=>{const pass={decision:'pass',confidence:.95,issues:[],summary:'隔离测试'};assert.equal(parseVisualReview(JSON.stringify(pass),[5]).status,'passed');for(const changed of [{...pass,issues:[{kind:'overlap',at:5,description:'字幕重复'}]},{...pass,confidence:.5},{...pass,confidence:20},{...pass,issues:null}])assert.equal(parseVisualReview(JSON.stringify(changed),[5]).status,'review_required');assert.equal(parseVisualReview('不是JSON',[5]).status,'review_required');});
test('同一成片使用持久回执，不重复调用模型',async t=>{let calls=0;const q=await fixture(t,async()=>{calls++;return {ok:true,json:async()=>({choices:[{message:{content:JSON.stringify({decision:'pass',confidence:.95,issues:[],summary:'隔离测试'})}}]})};});const args={filePath:'fixture',sha256:'a'.repeat(64),product:'黑晶面膜',timeline,runId:'batch'};assert.equal((await q.assess(args)).status,'passed');assert.equal((await q.assess(args)).status,'passed');assert.equal(calls,1);});
test('模型结果不明不重复计费，每批最多四次内容调用',async t=>{let calls=0;const q=await fixture(t,async()=>{calls++;throw Error('simulated network uncertainty');});const args={filePath:'fixture',product:'黑晶面膜',timeline,runId:'batch'};for(let i=0;i<5;i++)assert.equal((await q.assess({...args,sha256:String(i).repeat(64)})).status,'review_required');assert.equal(calls,4);await q.assess({...args,sha256:'0'.repeat(64)});assert.equal(calls,4);});
test('连接未配置时不抽帧、不请求模型、不冒充自动内容合格',async t=>{let called=false;const q=await fixture(t,async()=>{called=true;});q.env={};const r=await q.assess({sha256:'b'.repeat(64),timeline});assert.equal(r.status,'review_required');assert.equal(called,false);});
test('存在当前活动依据缺口时阻断，且不消耗一次视觉模型调用',async t=>{let called=false;const q=await fixture(t,async()=>{called=true;throw Error('must not call');});const result=await q.assess({filePath:'fixture',sha256:'c'.repeat(64),product:'黑晶面膜',timeline:[{...timeline[0],sourceText:'周年庆直降一折！'}],runId:'batch'});assert.equal(result.reason,'business_fact_attention');assert.equal(result.issues[0].kind,'offer_basis_missing');assert.equal(called,false);});
