// Runs the real original-run scheduler and renderer with isolated media/provider
// doubles. It never calls a production model or registers a real business job.
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import {createHash} from 'node:crypto';
import {createClipRemixService} from '../clip-remix-service.mjs';
import {VisualQuality,VISUAL_REVIEW_VERSION,parseVisualReview} from '../visual-quality.mjs';
import {assessBatch} from '../batch-visual-quality.mjs';
const sha=x=>createHash('sha256').update(x).digest('hex');
for(const skuKnown of [true,false])test(`实际原run双成片渲染接批量审核：SKU${skuKnown?'已核验一请求两独立回执':'未知不收费不放行'}`,async t=>{
 const dataDir=await fs.mkdtemp(path.join(os.tmpdir(),'wis-real-service-batch-'));t.after(()=>fs.rm(dataDir,{recursive:true,force:true}));const root=path.join(dataDir,'clip-remix');for(const name of ['sources','clips','outputs','visual-reviews'])await fs.mkdir(path.join(root,name),{recursive:true});
 const sourceBytes=Buffer.from('isolated approved source bytes'),sourceHash=sha(sourceBytes),sku=skuKnown?'isolated-confirmed-sku':null;
 const source={id:'source',storedName:'source.mp4',originalName:'isolation source',visibility:'team',productCategory:'黑晶面膜',durationSeconds:60,hasAudio:true,contentSha256:sourceHash,skuVersion:sku,analysisAsrEvidence:{skuVersion:sku,sourceSha256:sourceHash},speechSegments:Array.from({length:4},(_,i)=>({id:'speech'+i,startSeconds:i*15,endSeconds:(i+1)*15,text:'打开包装，取出面膜，观察贴合状态。'}))};
 const clips=['hook','hook','solution','cta'].map((role,i)=>({id:'clip'+i,storedName:'clip'+i+'.mp4',name:'隔离测试切片'+i,sourceId:'source',visibility:'team',productCategory:'黑晶面膜',durationSeconds:15,startSeconds:i*15,endSeconds:(i+1)*15,role,reviewStatus:'approved',boundaryEvidence:{skuVersion:sku,sourceSha256:sourceHash},reviewedAt:'2026-01-01T00:00:00Z',tags:[]}));
 const framework={id:'framework',name:'隔离框架',visibility:'team',slots:['hook','solution','cta'].map(id=>({id,label:id})),tags:[]};
 const run={id:'original-run',status:'awaiting_review',dateKey:'2026-09-09',targetCount:2,targetDurationSeconds:45,renderIds:[],slotSelections:{hook:['clip0','clip1'],solution:['clip2'],cta:['clip3']},generatedCount:0,failedCount:0,attemptedCount:0,startCursor:0};
 const job={id:'original-job',name:'隔离原任务',createdById:'fixture-owner',createdByName:'Isolation',status:'paused',scheduleEnabled:false,nextRunAt:null,frameworkId:framework.id,productCategory:'黑晶面膜',dailyTarget:2,targetDurationSeconds:45,includeUsageDisclaimer:true,usageDisclaimerText:'产品使用效果因人而异',autoApproveOutputs:true,autoReturnAfterApproval:false,qianchuanDelivery:{enabled:false},sourceSelectionLimit:1,runs:[run]};
 await fs.writeFile(path.join(root,'sources/source.mp4'),sourceBytes);for(const clip of clips)await fs.writeFile(path.join(root,'clips',clip.storedName),clip.id);
 const libraryPath=path.join(root,'library.json');await fs.writeFile(libraryPath,JSON.stringify({version:7,sources:[source],clips,frameworks:[framework],renders:[],autoJobs:[job],folders:[]}));
 const budgetFiles=[];for(let i=0;i<3;i++){const file=path.join(root,'visual-reviews',`budget-${sha(run.id)}-${i}.json`),bytes=Buffer.from(JSON.stringify({original:true,slot:i}));await fs.writeFile(file,bytes);budgetFiles.push([file,bytes]);}
 let calls=0,batchCount=0,outputsAtFetch=0;
 t.mock.method(VisualQuality.prototype,'assess',async()=>{throw Error('Pair must not use two single-output requests');});
 t.mock.method(VisualQuality.prototype,'assessBatch',async function(args){batchCount++;assert.equal(args.runId,run.id);assert.equal(args.outputs.length,2);const quality={directory:this.directory,run:this.run,ffmpeg:this.ffmpeg,enabled:true,env:{WIS_REMIX_VISUAL_REVIEW_ENABLED:'true',JUMP_LLM_URL:'https://example.invalid/fixture',JUMP_LLM_TOKEN:'isolated-only',JUMP_LLM_APPLICATION:'fixture',JUMP_LLM_PROVIDER:'fixture',JUMP_LLM_VISION_MODEL:'fixture'},fetch:async(_url,opts)=>{
  calls++;outputsAtFetch=(await fs.readdir(path.join(root,'outputs'))).filter(n=>n.endsWith('.mp4')).length;const before=JSON.parse(await fs.readFile(libraryPath));assert.equal(before.renders.length,0,'No interim technical-only approval persisted');
  const request=JSON.parse(JSON.parse(opts.body).requests_data.messages[1].content[0].text);return {ok:true,json:async()=>({choices:[{message:{content:JSON.stringify({batchKey:request.batchKey,runId:request.runId,product:request.product,skuVersion:request.skuVersion,outputs:request.outputs.map(o=>({...o,decision:'pass',confidence:.98,summary:'隔离逐片通过',issues:[]}))})}}]})};
 }};return assessBatch(quality,args,{version:VISUAL_REVIEW_VERSION,parseReview:parseVisualReview});});
 const service=createClipRemixService({dataDir,nowIso:()=>new Date().toISOString(),inspectMedia:async()=>({duration:45,width:1080,height:1920,hasAudio:true,frameRate:30}),makeSegment:async()=>{throw Error('No new source or slice is needed');},runFfmpeg:async args=>fs.writeFile(args.at(-1),'isolated rendered output '+path.basename(args.at(-1))),runProcess:async(_cmd,args)=>{if(args.includes('-frames:v'))await fs.writeFile(args.at(-1),Buffer.concat([Buffer.from([255,216]),Buffer.from('sample '+args[args.indexOf('-ss')+1]),Buffer.from([255,217])]));return {stdout:'',stderr:''};},readJsonBody:async r=>r.body||{},jsonResponse:(res,status,body)=>Object.assign(res,{status,body}),autoRemixAdminUsers:'fixture-owner',materialCenter:{configured:false},cutter:{configured:false}});
 await service.initialize();const response={};await service.route({method:'POST',headers:{},body:{}},response,new URL('http://localhost/api/remix/automation/jobs/original-job/run-now'),{sub:'fixture-owner',name:'Isolation'});assert.equal(response.status,200,JSON.stringify(response));
 let final;for(let i=0;i<150;i++){await new Promise(r=>setTimeout(r,20));final=JSON.parse(await fs.readFile(libraryPath));if(batchCount&&service.runtimeState().activeAutoJobCount===0)break;}
 assert.equal(batchCount,1,JSON.stringify(final.autoJobs));assert.equal(final.autoJobs.length,1);assert.equal(final.autoJobs[0].runs.length,1);assert.equal(final.autoJobs[0].runs[0].id,run.id);assert.equal(final.renders.length,1);assert.equal(final.renders[0].variants.length,2);assert.equal(final.renders[0].automation.runId,run.id);assert.equal(calls,skuKnown?1:0);if(skuKnown)assert.equal(outputsAtFetch,2);
 for(const variant of final.renders[0].variants){assert.equal(variant.automaticAssessment.autoApproved,skuKnown);assert.equal(variant.reviewStatus,skuKnown?'approved':'changes_requested');if(skuKnown){assert.equal(variant.automaticAssessment.visualReview.coverage.length,3);assert.equal(variant.automaticAssessment.visualReview.sha256,variant.contentSha256);}}
 assert.equal((await fs.readdir(path.join(root,'visual-reviews'))).filter(n=>n.startsWith('budget-')).length,skuKnown?4:3);for(const [file,bytes]of budgetFiles)assert.deepEqual(await fs.readFile(file),bytes);
});
