import test from 'node:test';import assert from 'node:assert/strict';
import {hasPassedVisualReview,needsVisualAttention} from '../output-quality.mjs';
import {VISUAL_REVIEW_VERSION} from '../visual-quality.mjs';
import {reconcileOutputApproval,outputApprovalProvenance} from '../clip-remix-service.mjs';
const review={status:'passed',sha256:'a'.repeat(64),version:VISUAL_REVIEW_VERSION,confidence:.95,issues:[]};
test('同SHA旧v1/v2或无版本缓存不能作现行自动通过，需重新复核',()=>{assert.equal(hasPassedVisualReview({visualReview:review},review.sha256),true);assert.equal(needsVisualAttention({automaticAssessment:{visualReview:review}}),false);for(const version of ['',undefined,'wis-visual-qc-20260908-v1','wis-visual-qc-20260908-v2']){const old={...review,version};assert.equal(hasPassedVisualReview({status:'passed',visualReview:old},review.sha256),false);assert.equal(needsVisualAttention({automaticAssessment:{visualReview:old}}),true);}});
test('现行版本仍要求原SHA、至少0.9及空问题集，不因技术分或人工通过冒充自动通过',()=>{for(const changes of [{sha256:'b'.repeat(64)},{confidence:.89},{issues:[{kind:'issue'}]},{status:'review_required'}])assert.equal(hasPassedVisualReview({status:'passed',visualReview:{...review,...changes}},review.sha256),false);assert.equal(hasPassedVisualReview({status:'passed'},review.sha256),false);assert.equal(needsVisualAttention({automaticAssessment:{visualReview:{status:'review_required',version:VISUAL_REVIEW_VERSION,reason:'technical_prerequisite'}}}),false);});
test('旧版本原审核状态备注时间和证据均保留，明确待重核而不计入当前自动通过',()=>{for(const status of ['approved','changes_requested']){const variant={reviewStatus:status,reviewNote:'原审核意见',reviewedAt:'2026-09-08T00:00:00Z',contentSha256:review.sha256,automaticAssessment:{status:'passed',autoApproved:true,visualReview:{...review,version:'wis-visual-qc-20260908-v2'}}};const old=structuredClone(variant);reconcileOutputApproval(variant,'2026-09-09T00:00:00Z');for(const key of ['reviewStatus','reviewNote','reviewedAt'])assert.equal(variant[key],old[key]);assert.deepEqual(variant.automaticAssessment.visualReview,old.automaticAssessment.visualReview);assert.equal(variant.automaticAssessment.autoApproved,false);assert.equal(variant.automaticPolicyRevalidation.required,true);assert.equal(outputApprovalProvenance(variant),null);const at=variant.automaticPolicyRevalidation.firstNotedAt;reconcileOutputApproval(variant,'2026-09-10T00:00:00Z');assert.equal(variant.automaticPolicyRevalidation.firstNotedAt,at);}});
test('新的现行版本通过才解除自动待重核；人工审核不冒充自动通过',()=>{const v={reviewStatus:'approved',contentSha256:review.sha256,automaticPolicyRevalidation:{required:true},automaticAssessment:{status:'passed',visualReview:review}};reconcileOutputApproval(v,'2026-09-09T00:00:00Z');assert.equal(v.automaticPolicyRevalidation.required,false);assert.equal(outputApprovalProvenance(v),'automatic');const h={...v,reviewMode:'human',automaticAssessment:{status:'review_required',visualReview:{...review,version:'v2'}}};assert.equal(outputApprovalProvenance(h),'human');});
